[tools]
"aqua:tree-sitter/tree-sitter" = "latest"
bat = "latest"
"cargo:sheldon" = "latest"
delta = "latest" # git-delta
eza = "latest"
fd = "latest"
fzf = "latest"
"github:tmux/tmux-builds" = "latest"
lazygit = "latest"
lua-language-server = "latest"
neovim = "nightly"
ripgrep = "latest"
yazi = "latest"
zoxide = "latest"
