[tools]
"aqua:tree-sitter/tree-sitter" = "latest"
bat = "latest"
"cargo:sheldon" = "latest"
delta = "latest" # git-delta
eza = "latest"
fd = "latest"
fzf = "latest"
"github:tmux/tmux-builds" = "latest"
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
golangci-lint = "latest"
lazygit = "latest"
lua-language-server = "latest"
neovim = "nightly"
ripgrep = "latest"
yazi = "latest"
zoxide = "latest"
golangci-lint-langserver = "latest"
node = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
lima = "latest"
colima = "latest"
docker-cli = "latest"
docker-compose = "latest"
lazydocker = "latest"
